sudo: required
os: osx
language: bash

before_install:
  - pwd
  - cd ../

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3 python || brew upgrade swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis python3 python || brew outdated swig sdl2 sdl2_image sdl2_ttf freetype openal-soft tinyxml glew libvorbis  python3 python
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - git clone --quiet --depth 1 https://github.com/fifengine/fifechan.git
  - mkdir build_fifechan || ls
  - cd build_fifechan
  - cmake ../fifechan
  - make
  - sudo make install
  - cd ..
  - git clone --quiet --depth 1 https://github.com/fifengine/fifengine.git
  - mkdir _build_fife || ls
  - cd _build_fife
  - which python3
  - cmake -Dbuild-library=ON -DPYTHON_EXECUTABLE=/usr/local/bin/python3 -Dcegui=OFF ../fifengine
  - make
  - sudo make install
  - cd ..
  - pwd

cache:
  directories:
  - /usr/local/*

before_script:
  - pwd
  - ls
  - pwd
  - python3 -c 'from fife import fife; print(fife.getVersion())'

script:
  - isort -c -rc horizons tests *.py
  - pycodestyle horizons tests *.py development
  - COVERAGE_FILE=.coverage.nongui pytest --verbose --cov --cov-report= -rs
  - RUNCOV=1 pytest --gui-tests tests/gui --verbose --cov --cov-report= -rs

after_success:
  - coverage combine
  - coveralls
